services:
  - type: web
    name: echodrive-av
    env: python
    plan: starter
    buildCommand: "pip install -r server/requirements.txt"
    startCommand: "gunicorn --chdir server app:app"
    autoDeploy: true
